name: Coverage
on:
  push:
    branches:
      - dev 
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v2
      with:
        python-version: "3.11"
        architecture: x64
    - run: pip install nox
    - run: nox -f noxfile_cov.py -p "3.11"
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}